apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Values.config.prefix }}-authenticator"
  namespace: "{{ .Values.config.namespace }}"
spec:
  forwardAuth:
    address: "{{ .Values.config.authenticatorUrl }}"
    trustForwardHeader: true
    authResponseHeaders:
      - X-User-Name
      - X-User-Email
      - X-User-ID
      - X-User-Status