apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Values.config.prefix }}-authenticator"
  namespace: default
spec:
  forwardAuth:
    address: http://authentication.microchess.svc.cluster.local/v1/auth/authorize/native
    trustForwardHeader: true
    authResponseHeaders:
      - X-User-Name
      - X-User-Email
      - X-User-ID
      - X-User-Status