apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{{ .Values.config.prefix }}-scaler"
  namespace: "{{ .Values.config.namespace }}"
spec:
  scaleTargetRef:
    name: "{{ .Values.config.prefix }}-dp"
  minReplicaCount: {{ .Values.replicas.min }}
  maxReplicaCount: {{ .Values.replicas.max }}
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
