apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: microchess-gameplay-scaler
spec:
  scaleTargetRef:
    name: microchess-gameplay-dp
  minReplicaCount: {{ .Values.replicas.min }}
  maxReplicaCount: {{ .Values.replicas.max }}
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
