apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: microchess-gameplay-cert
  namespace: microchess-gameplay
spec:
  secretName: microchess-gameplay-tls
  issuerRef:
    name: certmanager-issuer
    kind: ClusterIssuer
  dnsNames:
    - api.microchess.fdero.com
