apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.config.prefix }}-dp"
  namespace: "{{ .Values.config.namespace }}"
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app: {{ .Values.config.prefix }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.prefix }}
    spec:
      containers:
      - name: gameplay
        image: "{{ .Values.image.registry }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        ports: 
          {{- .Values.ports | toYaml | nindent 10 }}
        resources: 
          {{- .Values.resources | toYaml | nindent 10 }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: RELEASE_DISTRIBUTION
            value: "name"
          - name: RELEASE_NODE
            value: "gameplay@$(POD_IP)"
          - name: MONGODB_URL
            value: "{{ .Values.config.mongodbUrl }}"