apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Values.config.prefix }}-https-redirect"
  namespace: "{{ .Values.config.namespace }}"
spec:
  redirectScheme:
    scheme: https
    permanent: true