#------------------------------------------------------#
#                         RUNTIME                      #
#------------------------------------------------------#

FROM alpine:latest

RUN apk add --no-cache \
    openssl            \
    ncurses-libs       \
    libstdc++          \
    libgcc

WORKDIR /app

COPY ./_build/prod/rel/microchess-gameplay ./

ENV port=80
ENV strategy="kube"

ENV MIX_ENV=prod
ENV RELEASE_DISTRIBUTION=name
ENV ERL_DIST_PORT=9000

EXPOSE 80 4369 9000

CMD ["bin/microchess-gameplay", "start"]