FROM alpine:latest

RUN apk add --no-cache openssl

WORKDIR /app

COPY _build/prod/rel/dero /app/_build/prod/rel/dero ./


ENV port=80
ENV strategy="kubernetes"

ENV MIX_ENV=prod
ENV ERL_AFLAGS="-kernel inet_dist_use_interface {0,0,0,0}"

EXPOSE 80 4369

CMD ["bin/dero", "start"]